### ISSUE TITLE
Gifts

### ISSUE THREAD

**Issue by esstorm** [BasicJavaElte/Java2017-1-Assignment-1#1]
Are the gifts supposed to be 1 gift assigned to 1 child, or just a general pool of gifts?
Also, is the isOlder meant to be run from the menu?

Thanks!

**Comment by ferraricharles** [comment]
**Are the gifts supposed to be 1 gift assigned to 1 child, or just a general pool of gifts?**
One pool of gifts is the default, in case you would like to get extra points, they should be assigned to one child.

**Is the isOlder meant to be run from the menu?**
Nope, isOlder is not requested to be on the menu, but, there is an option to sort by date so... ;)

**Comment by esstorm** [comment]
Thanks :)
